# Generated by Django 5.0.4 on 2024-04-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myresearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rs_nameth', models.CharField(max_length=100)),
                ('rs_fname_th', models.CharField(max_length=500)),
                ('rs_lname_th', models.CharField(max_length=500)),
                ('rs_year', models.SmallIntegerField()),
                ('rs_budget', models.SmallIntegerField()),
                ('rs_file', models.CharField(max_length=250)),
            ],
        ),
    ]
